### PR TITLE
Update aws libs & release 0.10.0

### PR DESCRIPTION
**Pull request by alexheretic**
Update _aws-sdk-dynamodb_ to `0.22` & release `0.10.0`.

cargo publish is currently a manual step that I can (still) do or someone at truelayer can do, let me know if you have a preference.

### CODE REVIEW

**Review by azanin — APPROVED** [review]

**Comment by azanin** [comment]
> Update _aws-sdk-dynamodb_ to `0.22` & release `0.10.0`.
> 
> cargo publish is currently a manual step that I can (still) do or someone at truelayer can do, let me know if you have a preference.

go for it. 👍

**Comment by suryapandian** [comment]
> Update _aws-sdk-dynamodb_ to `0.22` & release `0.10.0`.
> 
> cargo publish is currently a manual step that I can (still) do or someone at truelayer can do, let me know if you have a preference.

can we add this in the CI? or is it not possible?

**Comment by conradludgate** [comment]
> > Update _aws-sdk-dynamodb_ to `0.22` & release `0.10.0`.
> > 
> > cargo publish is currently a manual step that I can (still) do or someone at truelayer can do, let me know if you have a preference.
> 
> can we add this in the CI? or is it not possible? Actually I dont know what `cargo publish` is, I am guessing it is creating a new tag/release for the library that pushes the lib to cloudsmit or some lib store 🤔 

`cargo publish` is what releases to crates.io. We have no shared credentials setup on crates.io so there's currently no way for us to automate this

**Comment by alexheretic** [comment]
Thanks guys, I have published `0.10.0` :rocket: 

I can't tag though any more, but I guess that's not strictly needed.

**Pull request merged**
